### ISSUE TITLE
Write thesis in latex but I wanna use oxforddown when thesis is finished !

### ISSUE THREAD

**Issue by aGIToz** [ulyngs/oxforddown#21]
Hey buddy,

Great project, thanks for this awesome work!

I have a question. I would like to write my thesis using oxforddown and generate an html version of it. But my professors would also like to work on my thesis and they are more comfortable with latex.

I would like to ask what are the possible options I have? Is it possible for me to write my thesis in a latex template and then, toward the end of my PhD, I convert everything to rmarkdown and then use oxforddown to generate html?

 What is the best strategy for me ? 

Kindly help.

**Comment by ulyngs** [comment]
One option that comes to mind:

1. Use oxforddown, but instead of markdown, just write plain latex in the chapters.
2. When your PhD thesis is finished, use [pandoc](https://pandoc.org) to convert the latex to markdown syntax

You will probably need to clean up the converted files manually, but pandoc should get you most of the way.
