### ISSUE TITLE
Font size figures lists

### ISSUE THREAD

**Issue by MalteHueckstaedt** [ulyngs/oxforddown#57]
Hello, is there a way to reduce the font size of the figures and table lists?

thank you very much, 
Malte

**Comment by ulyngs** [comment]
Hi Malte,

it seems the `tocloft` LaTeX package can be used for this (https://mirror.ox.ac.uk/sites/ctan.org/macros/latex/contrib/tocloft/tocloft.pdf).

That is, try to add something like

```latex
\usepackage{tocloft}
\renewcommand\cftfigfont{\tiny}
```

in **templates/template.tex**

It seems it'll require some more thought, because as far as I can see, using the tocloft package has the side effect of changing the style of the headers in the table of contents, list of figures, and list of tables, so you'll need to figure out how to set that back to its original style, which will probably require some digging through **ociamthesis.cls**, which I haven't got time to do myself at the moment!

**Comment by MalteHueckstaedt** [comment]
Hi @ulyngs , 
perfect, thanks for the hint, that helps a lot!
