### ISSUE TITLE
Looking for guidance to adapt oxforddown to local university

### ISSUE THREAD

**Issue by jfrogren** [ulyngs/oxforddown#65]
Hi,

I am a PhD student who would be grateful for some support in order to adapt the thesisdown template to the LaTeX thesis template used at Lund University (LU), Sweden. The LU template can be reached from [here](https://github.com/ismayc/thesisdown/files/9621307/LaTeXavhandlingsmall.zip) or [here](https://www.overleaf.com/latex/templates/lund-university-licentiate-and-phd-thesis-template/hgcpwgzvxxnp). I have tried to find ways to enter the LaTeX code inside your template but have too little knowledge about LaTeX to know where to really start. Would very much appriciate if you (or someone else) could provide me with some guidance. Thanks!

/jfrogren

**Comment by ulyngs** [comment]
Is the information here sufficient: https://ulyngs.github.io/oxforddown/customisations-and-extensions.html#customising-to-a-different-university

**Comment by jfrogren** [comment]
Unfortunately not since the LU template is not limited to a single `.tex` file but several files in different folders. I have posted a question over at [Stackoverflow](https://stackoverflow.com/questions/73875171/problems-in-getting-front-matter-toc-and-headings-right-when-adapting-bookdown) about this issue and there I also provide some more details about the results of my latest efforts. Would be very grateful for some guidance and to continue the conversation over there. Thanks a lot.

**Comment by ulyngs** [comment]
The Lund template looks very nice!

Here's some initial thoughts on different options:

- the very easy way: are you *required* to use the LU template? could you just use the Lund logo in oxforddown, and add in the page with the table (page 3-ish) from Overleaf?
- the easy, probably not-so-pretty-looking way: just use the LU template on Overleaf to output the first four or so pages as PDF; then modify the oxforddown template to start with including those PDF pages. This should work, but will mix the LU style with the oxforddown style
- the easy-medium way: find the font instructions in the oxforddown template and add those to the LU template, so that you can create a PDF of the front matter from the LU template in a way that looks a bit more like the oxforddown template
- medium way: go over the LU template, extract the parts you need, and insert it in oxforddown, replacing the relevant parts (require you to know how latex and the templates work)
