### ISSUE TITLE
fresh downloaded oxforddown not building

### ISSUE THREAD

**Issue by agamat** [ulyngs/oxforddown#89]
hi,

maybe it is only issue with my software but freshly downloaded oxforddown gives me:

! Undefined control sequence.
l.433 Welcome to \texttt{oxforddown} (\citeproc
                                               {ref-lyngsOxforddown2019}{Lyn...

Error: LaTeX failed to compile _main.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See _main.log for more info.
Execution halted

seems issue with \citeproc...

searching for solution but if you have it first, it would be even better

**Comment by meimeimei000** [comment]
I have the same problem. 
When kniting inidividal chapters with citations the error is: 

! LaTeX Error: Lonely \item--perhaps a missing list environment.

Error: LaTeX failed to compile 03-rmd-basics-cites-and-refs.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See 03-rmd-basics-cites-and-refs.log for more info.
Execution halted

Some people suggested since Pandoc 3.1.7, the team has changed the citation rendering of the LaTeX exporter. Therefore, manually installing the most recent Pandoc version or use an older version might help. My pandoc version is 3.1.11. I will try to update it to the newest, but my computer is admin password protected, need to hunt down the IT to intall it. If you are able to try before me, let me know how it goes. 

> hi,
> 
> maybe it is only issue with my software but freshly downloaded oxforddown gives me:
> 
> ! Undefined control sequence. l.433 Welcome to \texttt{oxforddown} (\citeproc {ref-lyngsOxforddown2019}{Lyn...
> 
> Error: LaTeX failed to compile _main.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See _main.log for more info. Execution halted
> 
> seems issue with \citeproc...
> 
> searching for solution but if you have it first, it would be even better

**Comment by ulyngs** [comment]
Hi @agamat apologies for the immense delay looking into this.

I just had a new computer and used that as an excuse to revisit oxforddown and ran into the issue you describe. It should be fixed now with [5cb486a](https://github.com/ulyngs/oxforddown/commit/5cb486adcd7ce7227bde1ea55c0c5f987dd016eb); try downloading a fresh copy and knitting!
